[package]
name = "tayori"
version = "0.1.0"
authors = ["Nathan Farrel <nathanfarrel1128@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "3"
members = [
  "migration",

  "crates/audio",
  "crates/core",
  "crates/detection",
  "crates/llm",
  "crates/rag",
  "crates/storage",
  "crates/stt",
]

[dependencies]
dioxus = { version = "0.7.7", features = [] }
lancedb = "0.27.2"
tayori_core = { path = "crates/core", package = "core" }
tokio = { version = "1.48.0", features = ["time"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[features]
default = ["desktop"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
