[application]
name = "tayori"

[bundle]
identifier = "com.tayori.app"

[web.app]

# HTML title tag content
title = "tayori-v2"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
