use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        create_settings(manager).await?;
        seed_settings(manager).await?;
        create_projects(manager).await?;
        create_sessions(manager).await?;
        create_documents(manager).await?;
        create_transcript_chunks(manager).await?;
        create_transcript_summaries(manager).await?;
        create_session_answers(manager).await?;

        create_indexes(manager).await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(SessionAnswers::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .drop_table(
                Table::drop()
                    .table(TranscriptSummaries::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .drop_table(
                Table::drop()
                    .table(TranscriptChunks::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;

        manager
            .drop_table(Table::drop().table(Documents::Table).if_exists().to_owned())
            .await?;

        manager
            .drop_table(Table::drop().table(Sessions::Table).if_exists().to_owned())
            .await?;

        manager
            .drop_table(Table::drop().table(Projects::Table).if_exists().to_owned())
            .await?;

        manager
            .drop_table(Table::drop().table(Settings::Table).if_exists().to_owned())
            .await?;

        Ok(())
    }
}

async fn create_settings(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Settings::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(Settings::Id)
                        .string()
                        .not_null()
                        .primary_key()
                        .check((
                            "ck_settings_id_default",
                            Expr::col(Settings::Id).eq("default"),
                        )),
                )
                .col(
                    ColumnDef::new(Settings::LlmProvider)
                        .string()
                        .not_null()
                        .check((
                            "ck_settings_llm_provider",
                            Expr::col(Settings::LlmProvider).is_in(["openai"]),
                        )),
                )
                .col(ColumnDef::new(Settings::LlmModel).string().not_null())
                .col(ColumnDef::new(Settings::LlmApiKeyRef).string().null())
                .col(
                    ColumnDef::new(Settings::LlmStoreResponses)
                        .integer()
                        .not_null()
                        .default(1)
                        .check((
                            "ck_settings_llm_store_responses",
                            Expr::col(Settings::LlmStoreResponses).is_in([0, 1]),
                        )),
                )
                .col(
                    ColumnDef::new(Settings::EmbeddingProvider)
                        .string()
                        .not_null()
                        .check((
                            "ck_settings_embedding_provider",
                            Expr::col(Settings::EmbeddingProvider).is_in(["fastembed"]),
                        )),
                )
                .col(ColumnDef::new(Settings::EmbeddingModel).string().not_null())
                .col(ColumnDef::new(Settings::SparseModel).string().not_null())
                .col(
                    ColumnDef::new(Settings::EmbeddingDimension)
                        .integer()
                        .not_null()
                        .default(768)
                        .check((
                            "ck_settings_embedding_dimension",
                            Expr::col(Settings::EmbeddingDimension).gt(0),
                        )),
                )
                .col(ColumnDef::new(Settings::RerankerModel).string().not_null())
                .col(
                    ColumnDef::new(Settings::WhisperModel)
                        .string()
                        .not_null()
                        .default("small-q8_0"),
                )
                .col(
                    ColumnDef::new(Settings::SummaryMinutes)
                        .integer()
                        .not_null()
                        .default(5)
                        .check((
                            "ck_settings_summary_minutes",
                            Expr::col(Settings::SummaryMinutes).between(1, 10),
                        )),
                )
                .col(
                    ColumnDef::new(Settings::UiTheme)
                        .string()
                        .not_null()
                        .default("light")
                        .check((
                            "ck_settings_ui_theme",
                            Expr::col(Settings::UiTheme).is_in(["dark", "light", "system"]),
                        )),
                )
                .col(
                    ColumnDef::new(Settings::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Settings::UpdatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .to_owned(),
        )
        .await
}

async fn seed_settings(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    let insert = Query::insert()
        .into_table(Settings::Table)
        .columns([
            Settings::Id,
            Settings::LlmProvider,
            Settings::LlmModel,
            Settings::LlmStoreResponses,
            Settings::EmbeddingProvider,
            Settings::EmbeddingModel,
            Settings::SparseModel,
            Settings::EmbeddingDimension,
            Settings::RerankerModel,
            Settings::WhisperModel,
            Settings::SummaryMinutes,
            Settings::UiTheme,
        ])
        .values_panic([
            "default".into(),
            "openai".into(),
            "gpt-4.1-mini".into(),
            1.into(),
            "fastembed".into(),
            "jinaai/jina-embeddings-v2-base-code".into(),
            "prithivida/splade_pp_en_v1".into(),
            768.into(),
            "jinaai/jina-reranker-v1-turbo-en".into(),
            "small-q8_0".into(),
            5.into(),
            "light".into(),
        ])
        .on_conflict(OnConflict::column(Settings::Id).do_nothing().to_owned())
        .to_owned();

    manager.execute(insert).await
}

async fn create_projects(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Projects::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(Projects::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(ColumnDef::new(Projects::Name).string().not_null())
                .col(ColumnDef::new(Projects::Description).text().null())
                .col(
                    ColumnDef::new(Projects::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Projects::UpdatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .to_owned(),
        )
        .await
}

async fn create_sessions(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Sessions::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(Sessions::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(ColumnDef::new(Sessions::ProjectId).string().not_null())
                .col(ColumnDef::new(Sessions::Title).string().null())
                .col(ColumnDef::new(Sessions::Status).string().not_null().check((
                    "ck_sessions_status",
                    Expr::col(Sessions::Status).is_in([
                        "running",
                        "completed",
                        "cancelled",
                        "failed",
                    ]),
                )))
                .col(
                    ColumnDef::new(Sessions::StartedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(ColumnDef::new(Sessions::EndedAt).timestamp().null())
                .col(
                    ColumnDef::new(Sessions::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Sessions::UpdatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_sessions_project_id")
                        .from(Sessions::Table, Sessions::ProjectId)
                        .to(Projects::Table, Projects::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await
}

async fn create_documents(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(Documents::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(Documents::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(ColumnDef::new(Documents::ProjectId).string().not_null())
                .col(ColumnDef::new(Documents::SourceName).string().not_null())
                .col(ColumnDef::new(Documents::OriginalPath).text().null())
                .col(ColumnDef::new(Documents::ContentHash).string().null())
                .col(
                    ColumnDef::new(Documents::Status)
                        .string()
                        .not_null()
                        .check((
                            "ck_documents_status",
                            Expr::col(Documents::Status).is_in(["ingesting", "ready", "failed"]),
                        )),
                )
                .col(ColumnDef::new(Documents::ErrorMessage).text().null())
                .col(
                    ColumnDef::new(Documents::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .col(
                    ColumnDef::new(Documents::UpdatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_documents_project_id")
                        .from(Documents::Table, Documents::ProjectId)
                        .to(Projects::Table, Projects::Id)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await
}

async fn create_transcript_chunks(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(TranscriptChunks::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(TranscriptChunks::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(TranscriptChunks::SessionId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptChunks::ProjectId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptChunks::ChunkIndex)
                        .integer()
                        .not_null(),
                )
                .col(ColumnDef::new(TranscriptChunks::Text).text().not_null())
                .col(
                    ColumnDef::new(TranscriptChunks::StartMs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptChunks::EndMs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptChunks::DurationMs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptChunks::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_transcript_chunks_session_project")
                        .from_tbl(TranscriptChunks::Table)
                        .from_col(TranscriptChunks::SessionId)
                        .from_col(TranscriptChunks::ProjectId)
                        .to_tbl(Sessions::Table)
                        .to_col(Sessions::Id)
                        .to_col(Sessions::ProjectId)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await
}

async fn create_transcript_summaries(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(TranscriptSummaries::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(TranscriptSummaries::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::ProjectId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::SessionId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::SummaryIndex)
                        .integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::ChunkStartIndex)
                        .integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::ChunkEndIndex)
                        .integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::StartMs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::EndMs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::DurationMs)
                        .big_integer()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::Summary)
                        .text()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(TranscriptSummaries::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_transcript_summaries_session_project")
                        .from_tbl(TranscriptSummaries::Table)
                        .from_col(TranscriptSummaries::SessionId)
                        .from_col(TranscriptSummaries::ProjectId)
                        .to_tbl(Sessions::Table)
                        .to_col(Sessions::Id)
                        .to_col(Sessions::ProjectId)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await
}

async fn create_session_answers(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_table(
            Table::create()
                .table(SessionAnswers::Table)
                .if_not_exists()
                .col(
                    ColumnDef::new(SessionAnswers::Id)
                        .string()
                        .not_null()
                        .primary_key(),
                )
                .col(
                    ColumnDef::new(SessionAnswers::ProjectId)
                        .string()
                        .not_null(),
                )
                .col(
                    ColumnDef::new(SessionAnswers::SessionId)
                        .string()
                        .not_null(),
                )
                .col(ColumnDef::new(SessionAnswers::Context).text().null())
                .col(ColumnDef::new(SessionAnswers::Query).text().not_null())
                .col(ColumnDef::new(SessionAnswers::Answer).text().not_null())
                .col(
                    ColumnDef::new(SessionAnswers::CreatedAt)
                        .timestamp()
                        .not_null()
                        .default(Expr::current_timestamp()),
                )
                .foreign_key(
                    ForeignKey::create()
                        .name("fk_session_answers_session_project")
                        .from_tbl(SessionAnswers::Table)
                        .from_col(SessionAnswers::SessionId)
                        .from_col(SessionAnswers::ProjectId)
                        .to_tbl(Sessions::Table)
                        .to_col(Sessions::Id)
                        .to_col(Sessions::ProjectId)
                        .on_delete(ForeignKeyAction::Cascade),
                )
                .to_owned(),
        )
        .await
}

async fn create_indexes(manager: &SchemaManager<'_>) -> Result<(), DbErr> {
    manager
        .create_index(
            Index::create()
                .name("idx_sessions_id_project_id")
                .table(Sessions::Table)
                .col(Sessions::Id)
                .col(Sessions::ProjectId)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_sessions_project_id")
                .table(Sessions::Table)
                .col(Sessions::ProjectId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_sessions_started_at")
                .table(Sessions::Table)
                .col(Sessions::StartedAt)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_documents_project_id")
                .table(Documents::Table)
                .col(Documents::ProjectId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_documents_status")
                .table(Documents::Table)
                .col(Documents::Status)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_documents_project_hash")
                .table(Documents::Table)
                .col(Documents::ProjectId)
                .col(Documents::ContentHash)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_chunks_project_id")
                .table(TranscriptChunks::Table)
                .col(TranscriptChunks::ProjectId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_chunks_session_id")
                .table(TranscriptChunks::Table)
                .col(TranscriptChunks::SessionId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_chunks_session_index")
                .table(TranscriptChunks::Table)
                .col(TranscriptChunks::SessionId)
                .col(TranscriptChunks::ChunkIndex)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_summaries_project_id")
                .table(TranscriptSummaries::Table)
                .col(TranscriptSummaries::ProjectId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_summaries_session_id")
                .table(TranscriptSummaries::Table)
                .col(TranscriptSummaries::SessionId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_summaries_session_summary")
                .table(TranscriptSummaries::Table)
                .col(TranscriptSummaries::SessionId)
                .col(TranscriptSummaries::SummaryIndex)
                .unique()
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_transcript_summaries_chunk_range")
                .table(TranscriptSummaries::Table)
                .col(TranscriptSummaries::SessionId)
                .col(TranscriptSummaries::ChunkStartIndex)
                .col(TranscriptSummaries::ChunkEndIndex)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_session_answers_project_id")
                .table(SessionAnswers::Table)
                .col(SessionAnswers::ProjectId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_session_answers_session_id")
                .table(SessionAnswers::Table)
                .col(SessionAnswers::SessionId)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    manager
        .create_index(
            Index::create()
                .name("idx_session_answers_created_at")
                .table(SessionAnswers::Table)
                .col(SessionAnswers::CreatedAt)
                .if_not_exists()
                .to_owned(),
        )
        .await?;

    Ok(())
}

#[derive(DeriveIden)]
enum Settings {
    Table,
    Id,
    LlmProvider,
    LlmModel,
    LlmApiKeyRef,
    LlmStoreResponses,
    EmbeddingProvider,
    EmbeddingModel,
    SparseModel,
    EmbeddingDimension,
    RerankerModel,
    WhisperModel,
    SummaryMinutes,
    UiTheme,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Projects {
    Table,
    Id,
    Name,
    Description,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Sessions {
    Table,
    Id,
    ProjectId,
    Title,
    Status,
    StartedAt,
    EndedAt,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum Documents {
    Table,
    Id,
    ProjectId,
    SourceName,
    OriginalPath,
    ContentHash,
    Status,
    ErrorMessage,
    CreatedAt,
    UpdatedAt,
}

#[derive(DeriveIden)]
enum TranscriptChunks {
    Table,
    Id,
    ProjectId,
    SessionId,
    ChunkIndex,
    Text,
    StartMs,
    EndMs,
    DurationMs,
    CreatedAt,
}

#[derive(DeriveIden)]
enum TranscriptSummaries {
    Table,
    Id,
    ProjectId,
    SessionId,
    SummaryIndex,
    ChunkStartIndex,
    ChunkEndIndex,
    StartMs,
    EndMs,
    DurationMs,
    Summary,
    CreatedAt,
}

#[derive(DeriveIden)]
enum SessionAnswers {
    Table,
    Id,
    ProjectId,
    SessionId,
    Context,
    Query,
    Answer,
    CreatedAt,
}
