//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::document_chunks::Entity as DocumentChunks;
pub use super::documents::Entity as Documents;
pub use super::projects::Entity as Projects;
pub use super::session_answers::Entity as SessionAnswers;
pub use super::sessions::Entity as Sessions;
pub use super::settings::Entity as Settings;
pub use super::transcript_chunks::Entity as TranscriptChunks;
