//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "sessions")]
pub struct Model {
    #[sea_orm(
        primary_key,
        auto_increment = false,
        unique_key = "idx_sessions_id_project_id"
    )]
    pub id: String,
    #[sea_orm(unique_key = "idx_sessions_id_project_id")]
    pub project_id: String,
    pub title: Option<String>,
    pub status: String,
    pub started_at: DateTimeUtc,
    pub ended_at: Option<DateTimeUtc>,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(has_many = "super::session_answers::Entity")]
    SessionAnswers,
    #[sea_orm(has_many = "super::transcript_chunks::Entity")]
    TranscriptChunks,
    #[sea_orm(has_many = "super::transcript_summaries::Entity")]
    TranscriptSummaries,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::session_answers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SessionAnswers.def()
    }
}

impl Related<super::transcript_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TranscriptChunks.def()
    }
}

impl Related<super::transcript_summaries::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TranscriptSummaries.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
