//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "settings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub llm_provider: String,
    pub llm_model: String,
    pub llm_api_key_ref: Option<String>,
    pub llm_store_responses: i64,
    pub embedding_provider: String,
    pub embedding_model: String,
    pub sparse_model: String,
    pub embedding_dimension: i64,
    pub reranker_model: String,
    pub whisper_model: Option<String>,
    pub summary_minutes: i64,
    pub ui_theme: String,
    pub created_at: DateTimeUtc,
    pub updated_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
