//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
#[sea_orm(table_name = "transcript_chunks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(unique_key = "idx_transcript_chunks_session_index")]
    pub session_id: String,
    pub project_id: String,
    #[sea_orm(unique_key = "idx_transcript_chunks_session_index")]
    pub chunk_index: i64,
    #[sea_orm(column_type = "Text")]
    pub text: String,
    pub start_ms: i64,
    pub end_ms: i64,
    pub duration_ms: i64,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::sessions::Entity",
        from = "(Column::SessionId, Column::ProjectId)",
        to = "(super::sessions::Column::Id, super::sessions::Column::ProjectId)",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Sessions,
}

impl Related<super::sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Sessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
