[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
hound = "3.5.1"
crossbeam-channel = "0.5.15"
ctrlc = "3.5.2"
audio = { path = "../audio" }
stt = { path = "../stt" }
ringbuf = "0.5.0"
